// Generated by CoffeeScript 1.7.1
(function() {
  var TEXT, TRM, TYPES, lineReader, njs_fs, rpr;

  TYPES = require('coffeenode-types');

  TRM = require('coffeenode-trm');

  TEXT = require('coffeenode-text');

  rpr = TRM.rpr.bind(TRM);

  njs_fs = require('fs');

  lineReader = require('line-reader');

  this.lines_of = function(route, handler) {
    var line_nr;
    line_nr = 0;
    return lineReader.eachLine(route, (function(_this) {
      return function(line, is_last_line) {
        line_nr += 1;
        handler(null, line, line_nr);
        if (is_last_line) {
          return handler(null, null);
        }
      };
    })(this));
  };

}).call(this);
